dataiku/dss-plugin-eks-clusters

README.md, code-env/python/desc.json, plugin.json, python-lib/dku_aws/aws_command.py, python-lib/dku_aws/eksctl_command.py, python-lib/dku_kube/kubectl_command.py, python-lib/dku_utils/access.py, python-runnables/test-network/runnable.py
=> Add Python3 compatibility

python-lib/dku_aws/aws_command.py, python-lib/dku_aws/eksctl_command.py, python-lib/dku_aws/eksctl_loader.py
Should work with both python2 and python3.
[sc-77298]
=> Fix several python3 str/bytes errors

CHANGELOG.md, Makefile, README.md, plugin.json
[sc-75346]
Added a changelog and updated the makefile according to: https://github.com/dataiku/dss-plugin-template
=> Bump version to 1.0.6, add changelog, update makefile

python-lib/dku_kube/autoscaler.py
Fixes [sc-83104]
The EKS plugin was using v1.12 of the cluster autoscaler. This did not allow me to scale nodegroups from zero nodes (assuming that there was already another nodegroup with at least one node; typical use-case GPU nodegroups).
https://docs.aws.amazon.com/eks/latest/userguide/autoscaling.html
I updated the autoscaler YAML using: https://raw.githubusercontent.com/kubernetes/autoscaler/master/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml
Note that I removed the following section from the cluster autoscaler "deployment" object, as these had also been removed in the previous YAML version of the plugin:
`      annotations:
prometheus.io/scrape: 'true'
prometheus.io/port: '8085'
spec:
priorityClassName: system-cluster-critical
securityContext: …
=> updated cluster autoscaler to v1.20.2

CHANGELOG.md, plugin.json
[SC-81997] just a small PR to review the changelog before the release.
=> [SC-81997] prepare plugin for release 1.0.8

CHANGELOG.md, plugin.json
update files in the plugin repository to prepare the release of version 1.0.9
=> prepare plugin release 1.0.9

CHANGELOG.md
=> [sc-107224] prepare release

python-clusters/attach-eks-cluster/cluster.py, python-clusters/create-eks-cluster/cluster.py
Reverts dataiku/dss-plugin-eks-clusters#41
=> Revert "[sc-49956] log API calls"

CHANGELOG.md, plugin.json, python-lib/dku_utils/config_parser.py
=> Add support on AWS intances requiring IMDS_v2

CHANGELOG.md, parameter-sets/node-pool-request/parameter-set.json, python-lib/dku_utils/node_pool.py
After discussion with Mickael, it has been decided to:
* keep field optional
* set min value to 0
* add documentation about the 0 meaning 200
* add comment in code and JSON about the default being used twice
=> [sc-150886] change default disk size to 200 gb

CHANGELOG.md, plugin.json
=> Bumping version to 1.2.3 for release

python-lib/dku_kube/gpu_driver.py
NVIDIA moved the nvidia-device-plugin.yml file, we have to move too.
=> New location for nvidia-device-plugin.yml

CHANGELOG.md, plugin.json
https://app.shortcut.com/dataiku/story/179642/eks-aks-nvidia-device-plugin-changed-location
=> Prepare EKS plugin for release

python-clusters/create-eks-cluster/cluster.py
=> [EKS] When advanced configuration is used and autoscaling activated, cluster creation fails

CHANGELOG.md, plugin.json, python-lib/dku_kube/gpu_driver.py
[sc-179642]
https://app.shortcut.com/dataiku/story/179642/eks-aks-nvidia-device-plugin-changed-location
=> Backport nvidia change loc dss11

python-clusters/create-eks-cluster/cluster.py
It is the same error as the one documented in the card but with another taints set
In the card, it was for the taints set for the autoscaler
Here, it is for the taints set for the GPUs
=> [sc-181246] initialize gpu taint set when advanced configuration is used

python-clusters/create-eks-cluster/cluster.py
https://app.shortcut.com/dataiku/story/201431/aks-eks-release-plugin
=> Ensure cluster has tags before using --tags option in config generation call

python-clusters/create-eks-cluster/cluster.py
For testing, create a cluster config (be careful, it must match the cluster name in the advanced config!!), and check the advanced mode, the autoscaler and the GPU support.
> TIP: Use eu-west-1a and eu-west-1c as availability zones for your subnets if you can. Those have the p3.2xlarge instances and eu-west-1b does not. It can lead to failures to create the cluster because there is no availability. That or use `aws ec2 describe-instance-type-offerings --region $AWS_REGION --location-type availability-zone --filters "Name=instance-type,Values=p3.2xlarge" --output table` to test which zones you can use for a different region.
> BETTER TIP: Use `g4dn.2xlarge` for the gpu type!
You can use this config (don't forget to replace the `<<placeholders>>`:
```yml
apiVersion: eksctl.io/v1alpha5
kind: …
```
=> Ensure the Nvidia driver is installed by eksctl for advanced configs

CHANGELOG.md, plugin.json
=> Update changelog and version for v1.4.4 release

.github/workflows/create-plugin-release.yml, Makefile, python-lib/dku_kube/gpu_driver.py
https://app.shortcut.com/dataiku/story/214284/eks-requests-2-32-3-is-a-huge-problem-with-github-leading-to-gpu-problem
=> Adding DSS plugin header for retrieving Nvidia driver & bundle driver in plugin as fallback

CHANGELOG.md, Makefile, python-clusters/create-eks-cluster/cluster.py, python-lib/dku_aws/eksctl_loader.py, python-lib/dku_kube/gpu_driver.py, python-lib/dku_utils/static_resources.py, python-runnables/install-alb-controller/runnable.py
Same fix as for the Nvidia config, but for the ALB controller files
=> Bundling ALB controller files as fallback
